version: '3.8'
services:


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile

    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"

  messaging-ms:
    build: ./messaging-ms
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fullstack24
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8084:8080"
    depends_on:
      - db
    networks:
      - backend-network

  doctorstaff-ms:
    build: ./doctorstaff-ms
    volumes:
      - ./backend:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fullstack24
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8083:8080"
    depends_on:
      - db
    networks:
      - backend-network
  

  patient-ms:
    build: ./patient-ms
    volumes:
      - ./backend:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fullstack24
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - backend-network



  user-ms:
    build: ./user-ms
    volumes:
      - ./backend:/app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fullstack24
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - backend-network


  image-ms:
    build: image-ms
    ports:
      - "3002:3002"
    networks:
      - backend-network
    depends_on:
      - db
    volumes:
      - ./image-ms/uploads:/app/uploads
      - ./image-ms:/app


  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fullstack24
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  db-data:
networks:
  backend-network: