apiVersion: v1
kind: Service
metadata:
  name: doctorstaff-ms
spec:
  selector:
    app: doctorstaff-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30005
  type: NodePort
  