apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: [ 'sh', '-c', 'until nc -zv db 3306; do echo "Waiting for db"; sleep 2; done;' ]
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          command: ["sh", "-c", "/opt/keycloak/bin/kc.sh start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              value: "mysql"
            - name: KC_DB_URL
              value: jdbc:mysql://db:3306/fullstack24
            - name: KC_DB_USERNAME
              value: user
            - name: KC_DB_PASSWORD
              value: password
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc


