apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-ms
  labels:
    app: messaging-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-ms
  template:
    metadata:
      name: messaging-ms
      labels:
        app: messaging-ms
    spec:
      containers:
        - name: messaging-ms
          image: backend-messaging-ms:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://db:3306/fullstack24
            - name: SPRING_DATASOURCE_USERNAME
              value: user
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
      restartPolicy: Always
      