apiVersion: v1
kind: Service
metadata:
  name: patient-ms
spec:
  selector:
    app: patient-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
  type: NodePort
  