name: Image

on:
  push:
    branches:
      - kthcloudtesta

jobs:

  image-ms-build:
    name: Build and Test Image Microservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use the version of Node.js that your project requires

      - name: Ensure Jest has executable permissions
        working-directory: backend/image-ms
        run: chmod +x node_modules/.bin/jest

      - name: Install Dependencies for Image Microservice
        working-directory: backend/image-ms
        run: npm install

      - name: Run Tests for image Microservice
        working-directory: backend/image-ms
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: fullstack24
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: robot$deploy-b23849a9-d97a-4b9e-bd06-a4bf766b28e1+fullstack24-imagenew
          password: 78BPIPEFoOAPluTuqZUrfacUF6gWJke9
          #username: ${{ secrets.DOCKER_USERNAME_IMAGE }}
          #password: ${{ secrets.DOCKER_PASSWORD_IMAGE }}

      - name: Build and push Image Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./backend/image-ms
          file: ./backend/image-ms/Dockerfile
          push: true
          tags: registry.cloud.cbh.kth.se/deploy-b23849a9-d97a-4b9e-bd06-a4bf766b28e1/fullstack24-imagenew
          #tags: ${{ secrets.DOCKER_TAG_IMAGE }}