name: Messaging

on:
  push:
    branches:
      - kthcloudtesta

jobs:

  messaging-ms-build:
    name: Build and Test Messaging Microservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build messaging Microservice
        working-directory: backend/messaging-ms
        run: mvn clean install -DskipTests

      - name: Run Tests for messaging Microservice
        working-directory: backend/messaging-ms
        run: mvn test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME_MESSAGING }}
          password: ${{ secrets.DOCKER_PASSWORD_MESSAGING }}

      - name: Build and push messaging Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./backend/messaging-ms
          file: ./backend/messaging-ms/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_TAG_MESSAGING }}
