name: Setup MySQL, Build, Test, and Push Docker Image

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      build-command:
        required: true
        type: string
      test-command:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      docker-tags:
        required: true
        type: string

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: fullstack24
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    steps:
      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin ping -h "127.0.0.1" --silent; do
            echo "Waiting for MySQL...";
            sleep 2;
          done

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Microservice
        run: ${{ inputs.build-command }}
        working-directory: ${{ inputs.working-directory }}

      - name: Run Tests
        run: ${{ inputs.test-command }}
        working-directory: ${{ inputs.working-directory }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.docker-tags }}
