name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  backend-build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Backend Docker Image
        working-directory: backend
        run: docker build -t backend:latest .

  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Frontend Docker Image
        working-directory: frontend
        run: docker build -t frontend:latest .

  docker:
    name: Test Docker Images
    runs-on: ubuntu-latest
    needs: [backend-build, frontend-build]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Backend Docker Container
        run: docker run -d --name backend-container backend:latest

      - name: Run Frontend Docker Container
        run: docker run -d --name frontend-container frontend:latest

      - name: Verify Containers Are Running
        run: |
          docker ps
