name: CI/CD Pipeline

on:
  push:
    branches:
      - unittests

jobs:
  start-database:
    name: Start MySQL Database
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin -h localhost -u root -ppassword ping --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done
          echo "MySQL is ready!"

  doctorstaff-ms-build:
    name: Build and Test Doctorstaff Microservice
    runs-on: ubuntu-latest
    needs: start-database

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Doctorstaff Microservice
        working-directory: backend/doctorstaff-ms
        run: mvn clean install -DskipTests

      - name: Run Tests for Doctorstaff Microservice
        working-directory: backend/doctorstaff-ms
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: user
          DB_PASSWORD: password
          DB_NAME: fullstack24
        run: mvn test


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Doctorstaff Microservice
        uses: docker/build-push-action@v5
        with:
          context: ./backend/doctorstaff-ms
          file: ./backend/doctorstaff-ms/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_TAG }}

