name: CI with Docker Compose

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: fullstack24
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to DockerHub (if you're using private images or need DockerHub authentication)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      # Build the Docker Compose services
      - name: Build and start Docker Compose services
        run: |
          docker-compose -f docker-compose.yml up -d

      # Run tests for each microservice

      - name: Run tests for messaging-ms
        run: |
          docker exec messaging-ms mvn test

      - name: Run tests for doctorstaff-ms
        run: |
          docker exec doctorstaff-ms mvn test

      - name: Run tests for patient-ms
        run: |
          docker exec patient-ms mvn test

      - name: Run tests for user-ms
        run: |
          docker exec user-ms mvn test

      - name: Run tests for image-ms
        run: |
          docker exec image-ms npm test

      # Shut down the containers after tests
      - name: Shutdown Docker Compose services
        run: |
          docker-compose -f docker-compose.yml down

      # Optionally, build and push Docker images to a registry (if needed)
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_TAG }}
