name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Test and Push Microservices
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d  

      # Doctorstaff Microservice
      - name: Build Doctorstaff Microservice
        working-directory: backend/doctorstaff-ms
        run: mvn clean install -DskipTests

      - name: Run Doctorstaff Microservice Tests
        working-directory: backend/doctorstaff-ms
        run: mvn test

      # Image Microservice
      - name: Build Image Microservice
        working-directory: backend/image-ms
        run: npm install

      - name: Run Image Microservice Tests
        working-directory: backend/image-ms
        run: npm test

      # Messaging Microservice
      - name: Build Messaging Microservice
        working-directory: backend/messaging-ms
        run: mvn clean install -DskipTests

      - name: Run Messaging Microservice Tests
        working-directory: backend/messaging-ms
        run: mvn test

      # Patient Microservice
      - name: Build Patient Microservice
        working-directory: backend/patient-ms
        run: mvn clean install -DskipTests

      - name: Run Patient Microservice Tests
        working-directory: backend/patient-ms
        run: mvn test

      # User Microservice
      - name: Build User Microservice
        working-directory: backend/user-ms
        run: mvn clean install -DskipTests

      - name: Run User Microservice Tests
        working-directory: backend/user-ms
        run: mvn test

      # Shutdown Docker Compose
      - name: Shut down Docker Compose
        run: docker-compose -f docker-compose.yml down

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push microservice images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_TAG }}
