name: CI/CD Pipeline

on:
  push:
    branches:
      - unittests

jobs:


  doctorstaff-ms-build:
    name: Build and Test Doctorstaff Microservice
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

      - name: Build the docker-compose stack
        run: |
          docker-compose -f ./backend/docker-compose.yaml up -d --build

      - name: Check running containers
        run: docker ps

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to DO Container Registry
        run: |
          docker tag mysql:8.0 ${{ secrets.DOCKER_TAG }}/mysql:8.0
          docker push ${{ secrets.DOCKER_TAG }}/mysql:8.0

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'

      - name: Push image to DO Container Registry
        run: |
          docker tag backend-doctorstaff-ms ${{ secrets.DOCKER_TAG }}/backend-doctorstaff-ms:latest
          docker push ${{ secrets.DOCKER_TAG }}/backend-doctorstaff-ms:latest

