name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  doctorstaff-ms-build:
    name: Build, Test, and Push Doctorstaff Microservice
    uses: ./.github/workflows/setup-mysql.yml
    with:
      working-directory: backend/doctorstaff-ms
      build-command: mvn clean install -DskipTests
      test-command: mvn test
      docker-context: ./backend/doctorstaff-ms
      dockerfile: ./backend/doctorstaff-ms/Dockerfile
      docker-tags: ${{ secrets.DOCKER_TAG }}

  image-ms-build:
    name: Build, Test, and Push Image Microservice
    uses: ./.github/workflows/setup-mysql.yml
    with:
      working-directory: backend/image-ms
      build-command: npm install
      test-command: npm test
      docker-context: ./backend/image-ms
      dockerfile: ./backend/image-ms/Dockerfile
      docker-tags: ${{ secrets.DOCKER_TAG }}

  messaging-ms-build:
    name: Build, Test, and Push Messaging Microservice
    uses: ./.github/workflows/setup-mysql.yml
    with:
      working-directory: backend/messaging-ms
      build-command: mvn clean install -DskipTests
      test-command: mvn test
      docker-context: ./backend/messaging-ms
      dockerfile: ./backend/messaging-ms/Dockerfile
      docker-tags: ${{ secrets.DOCKER_TAG }}

  patient-ms-build:
    name: Build, Test, and Push Patient Microservice
    uses: ./.github/workflows/setup-mysql.yml
    with:
      working-directory: backend/patient-ms
      build-command: mvn clean install -DskipTests
      test-command: mvn test
      docker-context: ./backend/patient-ms
      dockerfile: ./backend/patient-ms/Dockerfile
      docker-tags: ${{ secrets.DOCKER_TAG }}

  user-ms-build:
    name: Build, Test, and Push User Microservice
    uses: ./.github/workflows/setup-mysql.yml
    with:
      working-directory: backend/user-ms
      build-command: mvn clean install -DskipTests
      test-command: mvn test
      docker-context: ./backend/user-ms
      dockerfile: ./backend/user-ms/Dockerfile
      docker-tags: ${{ secrets.DOCKER_TAG }}
